### ISSUE TITLE
Update pydicom to version 2.2

### ISSUE THREAD

**Issue by ZviBaratz** [open-dicom/dicom_parser#108]
Updating causes breaking changes.

**Comment by taleinat** [comment]
@ZviBaratz, could you elaborate on the breaking changes?

What would it take to get this done?

**Comment by ZviBaratz** [comment]
@taleinat thank you for reaching out! 
Updating `pydicom` past 2.1.2 causes the tests to fail due to various changes made to the values returned for Siemens DWI series, as well as `PersonName` (`PN`) data elements:
```bash
====================================================================================== short test summary info ======================================================================================
FAILED tests/test_header.py::HeaderTestCase::test_get_data_elements_with_exclude_list - AssertionError: 83 != 59
FAILED tests/test_header.py::HeaderTestCase::test_get_data_elements_with_vr_list - AssertionError: 26 != 20
FAILED tests/test_image.py::ImageTestCase::test_b_matrix - AssertionError: False is not true
FAILED tests/test_image.py::ImageTestCase::test_b_vector - ValueError: shapes (6,) and (3,3) not aligned: 6 (dim 0) != 3 (dim 0)
FAILED tests/test_image.py::ImageTestCase::test_q_vector - ValueError: shapes (6,) and (3,3) not aligned: 6 (dim 0) != 3 (dim 0)
FAILED tests/test_image.py::ImageTestCase::test_voxel_space_b_matrix - ValueError: shapes (6,) and (3,3) not aligned: 6 (dim 0) != 3 (dim 0)
FAILED tests/data_elements/test_person_name.py::PersonNameTestCase::test_parse_value - AssertionError: {'name_prefix': '', 'given_name': '', 'mid[47 chars]: ''} != {}
FAILED tests/data_elements/test_private_data_element.py::SiemensTestCase::test_parse_value - AssertionError: (1.0, 1.0, 1.0, 1.0, 1.0, 1.0) != array([[1., 1., 1.],
==================================================================== 8 failed, 269 passed, 212 skipped, 23036 warnings in 8.12s =====================================================================
```
It seems `pydicom` added some automatic parsing functionality that behaves differently than `dicom_parser`. 
What's required now is to:
- [ ] Check the differences between how `pydicom` parses out the relevant elements before 2.2.* and after.
- [ ] Understand why it is different than `dicom_parser`'s logic and choose the correct/preferred parsing strategy.
- [ ] Change `dicom_parser`'s parsing logic accordingly.
- [ ] Update requirements to require `dicom_parser>=2.2.*` or customize parsing logic based on `pydicom` version and remove the existing limitation in the dependencies.

Hope this is clearer, any help would be greatly appreciated.

**Comment by taleinat** [comment]
The PersonName issue is pretty simple: For an empty value (""), pydicom 2.2 now returns a PersonName object, while 2.1 returned an empty string. A nice solution would be to always convert empty strings to `PersonName("")` and then parse that, which would provide nice consistency.

**Comment by taleinat** [comment]
Would we also want to add testing with both pydicom 2.1. and 2.2.x?

**Comment by ZviBaratz** [comment]
> The PersonName issue is pretty simple: For an empty value (""), pydicom 2.2 now returns a PersonName object, while 2.1 returns an empty string. A nice solution would be to always convert empty strings to `PersonName("")` and then parse that, which would provide nice consistency.

Sounds good. Unfortunately, I expect the b-vector/matrix stuff might not be as straightforward. Any ideas regarding those?

> If supporting pydicom 2.1 is desirable, would we also want to add testing with both pydicom 2.1.x and 2.2.x? (And soon 2.3.x since that has been released too?)

Indeed. It isn't currently integrated into the CI, but I do think it would be best to try and keep pydicom version support as broad as possible. It is a commonplace dependency and could otherwise easily conflict with other projects.

**Comment by taleinat** [comment]
> Sounds good. Unfortunately, I expect the b-vector/matrix stuff might not be as straightforward. Any ideas regarding those?

I wanted to start with something simple while I make myself familiar with this codebase. I'll try to take a look at those next!

**Comment by taleinat** [comment]
So, the here's the issue with the Siemens B-vector:

pydicom 2.1.x returns the VR "UN" (unknown) and the data as an array of 48 bytes. dicom_parser's `parse_siemens_b_matrix()` then converts that into an `array.array` of 6 double-precision floats, which is then tranformed into a 3x3 ndarray with some values being repeated (according to the indexes in `B_MATRIX_INDICES`).

pydicom 2.2.x returns the VR "FD" (double-precision float) and the data as a list of 6 floats. `parse_siemens_b_matrix()` doesn't know how to handle that so it returns it as-is.

It seems that the best way to handle this is to update `parse_siemens_b_matrix()` to properly handle both cases.
