### ISSUE TITLE
Support Siemens DICOM ".IMA" file extension 

### ISSUE THREAD

**Issue by liamtimms** [open-dicom/dicom_parser#109]
**Describe the bug**
Siemens scanners export scans as DICOM series with the ".IMA" file extension. Most other DICOM-oriented tools I've tested support this alternate file extension. In fact, `dicom_parser` can access the headers from these files when directed to them individually.  However, these are excluded from the rglob call in `get_dcm_paths()` of `series.py` causing `dicom_parser` to incorrectly identify DICOM folders with .IMA files as "EMPTY_SERIES_DIRECTORY"

**To Reproduce**
Attempt to load a series with the .IMA Siemens DICOM extension.

**Expected behavior**
To load the series regardless of files being labeled with ".IMA", ".DCM", ".dcm" or ".ima".

**Additional context**
I naively just added a second rglob call to solve this in a fork  (5d9986ae0d3788eca5b2376286798d05e6609699). That solves it for my use case but might not be a truly general solution.

**Comment by ZviBaratz** [comment]
Hi @liamtimms, thank you for reporting!
It definitely makes sense to add *.ima* as an extension that is included by default. However, I'd also like to suggest using `mime=True` when instantiating the image, this should also work for this use-case.

**Comment by ZviBaratz** [comment]
@liamtimms please confirm [installing from the main branch](https://github.com/open-dicom/dicom_parser#installation) solves the issue.

**Comment by liamtimms** [comment]
Seems to work as expected. Thank you!
