### ISSUE TITLE
"ImageType" not set causes is_mosaic to crash

### ISSUE THREAD

**Issue by Thothore** [open-dicom/dicom_parser#78]
**Is your feature request related to a problem? Please describe.**
My dicoms don't have any "ImageType" field so I cannot use .data on them I have to work with raw

**Describe the solution you'd like**
To have a more robust check, as the only purpose is to know if it is mosaic or not, just consider that it is not if "ImageType" is not present (maybe raise a warning)

**Describe alternatives you've considered**
Changing manually the header of the dicom, can be tedious 

**Additional context**
![image](https://user-images.githubusercontent.com/35405712/138717376-1ebe70ff-1544-4843-89e9-172233abd8d2.png)

**Comment by ZviBaratz** [comment]
Hi @Thothore, so sorry for the late response, I somehow missed you opening this. Also, thank you for reporting, this could definitely be handled more robustly. What you proposed (assuming not mosaic if not present) sound reasonable. I'll try and merge a fix soon.
