### ISSUE TITLE
Fix phase encoding property

### ISSUE THREAD

**Issue by ZviBaratz** [open-dicom/dicom_parser#81]
The current implementation is experimental (i.e. I am still trying to figure out how to translate the spatial information in the header to AP/PA/LR/RL labels that can used to generate BIDS-compatible relative paths).

**Comment by ZviBaratz** [comment]
@magerkurth I actually ended up simply encoding it as `FWD` and `REV` (see [this discourse discussion](https://nipy.discourse.group/t/siemens-diffusion-phase-encoding-directionality/84/7)) which seems to work well enough. I'm definitely not against fixing it up to provide `AP`/`PA`/`RL`/`LR` labels, but I'm not entirely convinced it's necessary.

**Comment by magerkurth** [comment]
Siemens encodes the direction in AP/PA/RL/LR on the Syngo GUI and if I am not wrong also in the PDF printout of the protocol. It would be a nice feature to match, but I agree may not be essential. However, I use your tool to generate PDFs with the most relevant values, to avoid generating PDFs from the console for researchers over and over again. For non physicist AP/PA/RL/LR would be easier to understand.

**Comment by ZviBaratz** [comment]
That makes sense. So glad to hear you find it useful. Please feel free to PR if you have an implementation in mind, I got a little lost trying to come up with something.

**Comment by magerkurth** [comment]
I have a lock I get on with the current possibilities of the code and discuss it further in at our lab. Thanks a lot for your quick answers.
