### ISSUE TITLE
PhaseEncodingDirectionPositive not extracted from CSA header

### ISSUE THREAD

**Issue by magerkurth** [open-dicom/dicom_parser#86]
**Describe the bug**
PhaseEncodingDirectionPositive not extracted from CSA header

**To Reproduce**

```
self._header = dicom_parser.Header(self._filename)
self._csa_header = dicom_parser.utils.siemens.csa.header.CsaHeader(self._header.get("CSASeriesHeaderInfo", parsed=False))
self._csa_header_parsed = self._csa_header.parsed
```

No key with "PhaseEncodingDirectionPositive" in the dictionary (or sub-diktioniers and lists) of self._csa_header_parsed

**Desktop:**
 - OS: Mac Monterey
 - Dockerised Python 3.10 with newest version of python_parser included in the Docker container via git command

**Prove that DICOM file contains "PhaseEncodingDirectionPositive"**
In a bash terminal execute:

`strings /incoming/dicom.dcm  | sort | grep -I phase`

This code finds a field "PhaseEncodingDirectionPositive"

**Further comments**
I was working on the problem of extracting the phase encoding direction, when I came across this issue. I have not checked if other fields are missing too, but that could be very well the case.

**Comment by ZviBaratz** [comment]
@magerkurth Thank you for reporting this!

Two comments:

* If I am not mistaken, the `PhaseEncodingDirectionPositive` CSA field is found in the `CSAImageHeaderInfo` (`(0029, 1010)`) and not `CSASeriesHeaderInfo` (`(0029, 1020)`) private tag (see the `Header` class' [`get_phase_encoding_direction`](https://github.com/open-dicom/dicom_parser/blob/acc82f6f989a335fd3cf30e716334081ab9ac43b/src/dicom_parser/header.py#L715) method. 
* The `CSAImageHeaderInfo` and `CSASeriesHeaderInfo` tags are parsed automatically, so you should be able to just do: `header.get("CSAImageHeaderInfo")` to return the parsed dictionary.

I think you should try:
```python
>>> header = dicom_parser.Header(path)
>>> csa_header = header.get("CSAImageHeaderInfo")
>>> csa_header.get("PhaseEncodingDirectionPositive")
{'index': 20, 'VR': 'IS', 'VM': 1, 'value': 1}
# Or, do return i/j/-/+:
>>> header.get_phase_encoding_direction()
'i-'
```

Does this work?

**Comment by magerkurth** [comment]
Hi,

Thank for the quick response. Oh dear, I have missed the "Image" instead of the "Series". I will try your suggestion after I am back from my annual leave.

Best wishes.

**Comment by magerkurth** [comment]
"Image" instead of "Series" did the trick.

However, `header.get("CSAImageHeaderInfo")` does not return a parsed object, but type byte. I can live with this, using the following work around. 
          
```
 self._csa_image_header = dicom_parser.utils.siemens.csa.header.CsaHeader(self._header.get("CSAImageHeaderInfo", parsed=False))
 logger.debug2('Parsing CSA Image header\n')
 self._csa_image_header_parsed = self._csa_image_header.read()
```

I am using the dicom_parser version from 19.02.

**Comment by ZviBaratz** [comment]
Ok, let me know how it goes. If it still doesn't work, I'd suggest trying to use the tag instead of the name (`("0029", "1010")`).

**Comment by ZviBaratz** [comment]
@magerkurth any updates? Can this be closed?
